language: node_js
node_js:
  - "lts/*"
cache: 
  yarn: true
  directories:
    - node_modules # NPM packages
before_install:
  - yarn global add rimraf webpack@1.13.3
install: 
  - yarn build
deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master