const prefix = '@@redux-form';

// @type 'redux-form/lib/actionTypes';
export default {
    ARRAY_INSERT: `${prefix}/ARRAY_INSERT`,
    ARRAY_MOVE: `${prefix}/ARRAY_MOVE`,
    ARRAY_POP: `${prefix}/ARRAY_POP`,
    ARRAY_PUSH: `${prefix}/ARRAY_PUSH`,
    ARRAY_REMOVE: `${prefix}/ARRAY_REMOVE`,
    ARRAY_REMOVE_ALL: `${prefix}/ARRAY_REMOVE_ALL`,
    ARRAY_SHIFT: `${prefix}/ARRAY_SHIFT`,
    ARRAY_SPLICE: `${prefix}/ARRAY_SPLICE`,
    ARRAY_UNSHIFT: `${prefix}ARRAY_UNSHIFT`,
    ARRAY_SWAP: `${prefix}/ARRAY_SWAP`,
    AUTOFILL: `${prefix}/AUTOFILL`,
    BLUR: `${prefix}/BLUR`,
    CHANGE: `${prefix}/CHANGE`,
    CLEAR_SUBMIT: `${prefix}/CLEAR_SUBMIT`,
    CLEAR_SUBMIT_ERRORS: `${prefix}/CLEAR_SUBMIT_ERRORS`,
    CLEAR_ASYNC_ERROR: `${prefix}/CLEAR_ASYNC_ERROR`,
    CLEAR_FIELDS: `${prefix}/CLEAR_FIELDS`,
    DESTROY: `${prefix}/DESTROY`,
    FOCUS: `${prefix}/FOCUS`,
    INITIALIZE: `${prefix}/INITIALIZE`,
    REGISTER_FIELD: `${prefix}/REGISTER_FIELD`,
    RESET: `${prefix}/RESET`,
    RESET_SECTION: `${prefix}/RESET_SECTION`,
    SET_SUBMIT_FAILED: `${prefix}/SET_SUBMIT_FAILED`,
    SET_SUBMIT_SUCCEEDED: `${prefix}/SET_SUBMIT_SUCCEEDED`,
    START_ASYNC_VALIDATION: `${prefix}/START_ASYNC_VALIDATION`,
    START_SUBMIT: `${prefix}/START_SUBMIT`,
    STOP_ASYNC_VALIDATION: `${prefix}/STOP_ASYNC_VALIDATION`,
    STOP_SUBMIT: `${prefix}/STOP_SUBMIT`,
    SUBMIT: `${prefix}/SUBMIT`,
    TOUCH: `${prefix}/TOUCH`,
    UNREGISTER_FIELD: `${prefix}/UNREGISTER_FIELD`,
    UNTOUCH: `${prefix}/UNTOUCH`,
    UPDATE_SYNC_ERRORS: `${prefix}/UPDATE_SYNC_ERRORS`,
    UPDATE_SYNC_WARNINGS: `${prefix}/UPDATE_SYNC_WARNINGS`,
}